### ISSUE TITLE
raster image is not re-rendered 

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#103]
with the following snippet there are two image re-rendering issues

```
img0 = session.open_image(image_file_7)
img1 = session.append_image(image_file_1)

img0.make_active() # issue1
img0.set_channel(20)
img0.set_polarization(Polarization.Q)

time.sleep(5) # issue2

img1.make_active()
img1.set_channel(20)
```

Issue1
In this case, img1 will be the active image. Then if I do img0.set_channel(20) and/or img0.set_polarization(Polarization.Q) without img0.make_active(), we will see indeed in the image list widget, the channel index and polarization string are updated. However, the rendered image is not. We need to do img0.make_active() first to re-render the raster image. I suggest in set_channel and set_polarization we internally make the target image as "active" before setting channel/polarization. In the scripting interface when there are multiple image loaded, it is non-trivial which one is currently "active" I suppose.

Issue2
In the above snippet, if I comment out time.sleep(5), even if we do img0.make_active() first before setting channel and polarization, we do not see img0 got re-rendered. I suspect this is an sync/async issue.

**Comment by confluence** [comment]
I'm concerned that making an inactive image active as a side effect of changing the channel / polarization is unexpected behaviour, and I would rather not do it by default.

I wonder if there's a way to force re-rendering in the frontend without making the image active.
