### ISSUE TITLE
refactor AST-overlay related functions 

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#119]
currently, AST-overlay related functions are part of the session object and to make a custom title of the image view, we do like `session.set_text(title='this is a new title')` which is less intuitive. It would be good to have a class for AST-overlay related settings (might be worth to have it as it is a relative complex one) and we can use the image object to call it to make changes to AST-overlay. Details to be discussed.

**Comment by confluence** [comment]
This will be resolved by #140.
