### ISSUE TITLE
"failed to connect to all addresses" after session.open_image(...)

### ISSUE THREAD

**Issue by lh-astro** [idia-astro/carta-python#23]
1. I run CARTA via:
`./CARTA-v3.0.0-beta.1b-ubuntu.AppImage`

2.1 In Firefox it starts up as expected.

3.1 Running the following python commands results in an error:
```
from carta.client import Session
session = Session.interact("localhost", 3002, 1, "a4e4effd-0a3d-433c-92a3-42ab185c2dae")
img1 = session.open_image("/tmp/test.fits")
```

4.1 The error message is:
```
>>> img1 = session.open_image("/tmp/test.fits")
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/carta/client.py", line 227, in call_action
    response = stub.CallAction(
  File "/home/user/.local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/user/.local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1631458120.050162760","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3186,"referenced_errors":[{"created":"@1631458120.050159206","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":146,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.9/site-packages/carta/validation.py", line 522, in newfunc
    return func(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/carta/client.py", line 371, in open_image
    return Image.new(self, path, hdu, False)
  File "/home/user/.local/lib/python3.9/site-packages/carta/client.py", line 740, in new
    path = session.resolve_file_path(path)
  File "/home/user/.local/lib/python3.9/site-packages/carta/client.py", line 292, in resolve_file_path
    return f"{self.pwd()}/{path}"
  File "/home/user/.local/lib/python3.9/site-packages/carta/client.py", line 303, in pwd
    self.call_action("fileBrowserStore.getFileList", Macro("fileBrowserStore", "startingDirectory"))
  File "/home/user/.local/lib/python3.9/site-packages/carta/client.py", line 233, in call_action
    raise CartaActionFailed(f"{carta_action_description} failed: {e.details()}") from e
carta.util.CartaActionFailed: CARTA scripting action fileBrowserStore.getFileList called with parameters [{"macroTarget": "fileBrowserStore", "macroVariable": "startingDirectory"}] failed: failed to connect to all addresses
```

2.2 Connecting via Chromium Version  93 shows the CARTA loading image for a split second and turns into a blank white screen.

2.3 The console output shows:
https://transfer.sh/sOHrTx/screenshot1.jpg
(Sorry, issues with github image upload. I'm going to fix that. Hope the link is good enough for now)
I suspect this issue (2.3) is not related to carta-python . I though it is still worth mentioning.

**Comment by confluence** [comment]
You need to start the backend with a `--grpc_port` parameter to enable the gRPC interface which the wrapper uses. I will make this explicit in the documentation. I recommend using `50051` by default, but it shouldn't matter what you use as long as it doesn't clash with anything.

When the backend is started with this parameter, a gRPC security token will be printed in the output. It is this token and the gRPC port that you need to enter as the port and token parameters to `interact`, not the websocket port and token.

In addition to explaining the port in the docs, I will see if I can make this error message more helpful.

If you start the CARTA backend and you are unable to open the frontend in Chromium, that is an unrelated issue. I suggest that you file it [in the main CARTA repo](https://github.com/CARTAvis/carta/issues/).

If you are using Ubuntu, I recommend installing CARTA [from the PPA](https://launchpad.net/~cartavis-team/+archive/ubuntu/carta) (the `carta-beta` metapackage will install the beta release that you need; both the backend and frontend components).

**Comment by confluence** [comment]
The documentation has been updated with information about the `--grpc_port` parameter.

**Comment by confluence** [comment]
This issue refers to an outdated API which is no longer supported.
