### ISSUE TITLE
ambiguous image.depth and image.stokes for 2D images

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#46]
```
    @property
    @cached
    def depth(self):
        """The depth of the image.

        Returns
        -------
        integer
            The depth.
        """
        return self.get_value("frameInfo.fileInfoExtended.depth")

    @property
    @cached
    def stokes(self):
        """The number of Stokes parameters of the image.

        Returns
        -------
        integer
            The number of Stokes parameters.
        """
        return self.get_value("frameInfo.fileInfoExtended.stokes")
```

When the image is 2D with `NAXIS=2`, image.depth is 1 and image.stokes is 1. This is a bit confusing. Would it be better if it is `None`? Or Is this a frontend issue?

Also I would suggest we change image.stokes to image.n_stokes.

**Comment by confluence** [comment]
I would say that a 2D image has a depth of 1 and a Stokes dimension of 1. I do agree about the `stokes` name; maybe `num_stokes`?

**Comment by kswang1029** [comment]
> I would say that a 2D image has a depth of 1 and a Stokes dimension of 1. I do agree about the `stokes` name; maybe `num_stokes`?

Ok and ok.
