### ISSUE TITLE
add Image.set_cube_matching as a shortcut to match image both spatially and spectrally

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#55]
add `Image.set_cube_matching` as a shortcut. Effectively, it does `Image.set_spatial_matching` and `Image.set_spectral_matching` together with the same input boolean. 

having a new `Image.make_cube_reference` as a shortcut of `Image.make_spatial_reference` and `Image.make_spectral_reference` is also nice to UX I think.

**Comment by confluence** [comment]
Should these also match the raster scaling / set the raster scaling reference? I can see the utility of functions that group all three settings, but I'm less convinced about functions that group 2 out of 3.

**Comment by kswang1029** [comment]
> Should these also match the raster scaling / set the raster scaling reference? I can see the utility of functions that group all three settings, but I'm less convinced about functions that group 2 out of 3.

I suggest we only group spatial and spectral matching. 

Well if you like we can also make a matching everything function. Then users can decide which one to use for their various use cases.
