### ISSUE TITLE
allowing world coordinates as input in Image.set_center()

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#56]
Currently, `Image.set_center()` takes two numbers as the image coordinates as the input. For a better usability, we will need to also support inputs as world coordinates such as:

`Image.set_center('12h34m.56.789s', '-10d20m30.45s')`
`Image.set_center('123.3456deg', '-12.3456deg')`

This may be straightforward once https://github.com/CARTAvis/carta-frontend/issues/1176 is implemented (otherwise we will need to handle image<->world coordinates transformation...)

**Comment by kswang1029** [comment]
this is now possible with the frontend based on https://github.com/CARTAvis/carta-frontend/pull/2081

**Comment by Jordatious** [comment]
Is the current input pixel units then?

**Comment by kswang1029** [comment]
> Is the current input pixel units then?

Yes

**Comment by Jordatious** [comment]
Ok thanks. The user could get around this with other WCS libraries, but certainly this would be a nice additional feature for CARTA.

**Comment by confluence** [comment]
Implemented in #116.
