### ISSUE TITLE
allowing angular size as input in Image.set_zoom()

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#57]
currently `Image.set_zoom()` takes the zoom factor as the input. This is not intuitive in general use cases and it depends on the screen resolution. The better inputs should be 1) in pixels to fill up the image view and 2) in angular size to fill up the image view. Examples:

`Image.set_zoom('123pix')`
`Image.set_zoom('20arcsec')`
`Image.set_zoom('4arcmin')`
`Image.set_zoom('2deg')`

This may be straightforward once https://github.com/CARTAvis/carta-frontend/issues/1176 is implemented (otherwise we will need to handle image<->world coordinates transformation...)

We can still keep the zoom factor as one kind of inputs.

**Comment by kswang1029** [comment]
this is now possible with the frontend based on https://github.com/CARTAvis/carta-frontend/pull/2081

**Comment by Jordatious** [comment]
Would this just Zoom, or change the actual size / shape of the viewer window? I think both are needed, meaning it should support two inputs for reshaping. An interactive (i.e. not headless) scripting session would support manual resizing of the viewer window.

**Comment by Jordatious** [comment]
At this point, the user could address this with trial and error, assuming any real number is accepted as input.

**Comment by confluence** [comment]
Implemented in #116.
