### ISSUE TITLE
generalizing Session.load_image() and Session.append_image() to allow loading multiple images in one call

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#76]
Currently Session.load_image() and Session.append_image() accept a path arg to load one image. Although users can create a list of path and use a loop to call Session.append_image() to load multiple images, it would be handy if we can generalize the path as a str or a list of str so users can load images in one function call.

**Comment by Jordatious** [comment]
Agreed. One helpful use case for this is when running the scripting interface for a CARTA controller remotely (e.g. from a laptop), where `*.fits` cannot be expanded remotely.

**Comment by confluence** [comment]
This function wouldn't allow the user to expand a wildcard either; the user would still have to provide all the individual file paths.

I'm not convinced that this function is necessary, and I don't think that it can cater for every possible way to open a single image (complex, LEL expression, using a different HDU...) without the addition of a lot of overhead and complicated parameter handling which would remove the advantage of having a single function.

But maybe it makes sense to have an `open_images` shortcut for the simplest case -- i.e. opening a lot of individual files with all the default settings. Then this could just take a list of strings as a parameter. For more complicated cases the user can use a loop or write out individual commands.

**Comment by kswang1029** [comment]
> This function wouldn't allow the user to expand a wildcard either; the user would still have to provide all the individual file paths.
> 
> I'm not convinced that this function is necessary, and I don't think that it can cater for every possible way to open a single image (complex, LEL expression, using a different HDU...) without the addition of a lot of overhead and complicated parameter handling which would remove the advantage of having a single function.
> 
> But maybe it makes sense to have an `open_images` shortcut for the simplest case -- i.e. opening a lot of individual files with all the default settings. Then this could just take a list of strings as a parameter. For more complicated cases the user can use a loop or write out individual commands.

then I would suggest we have a `open_images` function to accept a list of path to support the simplest use case without detailed configuration for _each_ image in the list.

**Comment by I-Chenn** [comment]
I suggest we do this after the merge of [PR#108](https://github.com/CARTAvis/carta-python/pull/108), since there are major configurations for the functions of opening images.

**Comment by confluence** [comment]
This will be resolved in #106.

**Comment by confluence** [comment]
Resolved in #106.
