### ISSUE TITLE
support vector overlay rendering

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#79]
Similar to the contour rendering, the Image class needs a set of low-level functions for configuration and a high-level wrapper of low-level functions.

**Comment by confluence** [comment]
This PR is dependent on frontend issue [#2140](https://github.com/CARTAvis/carta-frontend/issues/2140). We can't get the intensity range to work correctly until that is fixed -- but once that's done it should be straightforward to finish this off.
